#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Mar 23, 2024 04:03:19 PM EDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 600x450+458+80
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3076 845
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    labelframe "$top.lab57" \
        -font "-family {Segoe UI} -size 11 -weight bold" -foreground #000000 \
        -text "Graphiques" -background #d9d9d9 -height 289 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 330 
    vTcl:DefineAlias "$top.lab57" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab57
    listbox "$site_3_0.lis77" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 -height 42 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 314 
    $site_3_0.lis77 configure -font "TkFixedFont"
    $site_3_0.lis77 insert end text
    vTcl:DefineAlias "$site_3_0.lis77" "Listbox3" vTcl:WidgetProc "Toplevel1" 1
    canvas "$site_3_0.can58" \
        -background #d9d9d9 -borderwidth 2 -closeenough 1.0 -height 289 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 668 
    vTcl:DefineAlias "$site_3_0.can58" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lis77 \
        -in $site_3_0 -x 0 -relx 0.03 -y 0 -rely 0.821 -width 0 \
        -relwidth 0.952 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_3_0.can58 \
        -in $site_3_0 -x 0 -relx 0.03 -y 0 -rely 0.082 -width 0 \
        -relwidth 0.949 -height 0 -relheight 0.717 -anchor nw \
        -bordermode ignore 
    labelframe "$top.lab52" \
        -font "-family {Segoe UI} -size 11 -weight bold" -foreground #000000 \
        -text "Masse active" -background #d9d9d9 -height 105 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 330 
    vTcl:DefineAlias "$top.lab52" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab52
    listbox "$site_3_0.lis75" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 -height 72 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 54 
    $site_3_0.lis75 configure -font "TkFixedFont"
    $site_3_0.lis75 insert end text
    vTcl:DefineAlias "$site_3_0.lis75" "Listbox2" vTcl:WidgetProc "Toplevel1" 1
    listbox "$site_3_0.lis76" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 -height 72 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 54 
    $site_3_0.lis76 configure -font "TkFixedFont"
    $site_3_0.lis76 insert end text
    vTcl:DefineAlias "$site_3_0.lis76" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -background #f9040b \
        -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000506 \
        -highlightbackground #d9d9d9 -highlightcolor #000506 -text "--- g" 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lis75 \
        -in $site_3_0 -x 0 -relx 0.818 -y 0 -rely 0.19 -width 0 \
        -relwidth 0.164 -height 0 -relheight 0.686 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lis76 \
        -in $site_3_0 -x 0 -relx 0.636 -y 0 -rely 0.19 -width 0 \
        -relwidth 0.164 -height 0 -relheight 0.686 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.03 -y 0 -rely 0.229 -width 0 \
        -relwidth 0.539 -height 0 -relheight 0.676 -anchor nw \
        -bordermode ignore 
    labelframe "$top.lab49" \
        -font "-family {Segoe UI} -size 11 -weight bold" -foreground #000000 \
        -text "Fonctions" -background #d9d9d9 -height 393 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 240 
    vTcl:DefineAlias "$top.lab49" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab49
    button "$site_3_0.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Étalonner" 
    vTcl:DefineAlias "$site_3_0.but51" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Tarer" 
    vTcl:DefineAlias "$site_3_0.but50" "Button1" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$site_3_0.lab79" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text "Moyennage" -background #d9d9d9 -height 95 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 220 
    vTcl:DefineAlias "$site_3_0.lab79" "Labelframe5" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab79
    message "$site_4_0.mes82" \
        -background #d9d9d9 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -padx 1 -pady 1 \
        -text "Entrer un nombre entier de mesures désirées pour moyenner la masse." \
        -width 200 
    vTcl:DefineAlias "$site_4_0.mes82" "Message1" vTcl:WidgetProc "Toplevel1" 1
    entry "$site_4_0.ent83" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -insertbackground #000000 -selectbackground #d9d9d9 \
        -selectforeground black -width 134 
    vTcl:DefineAlias "$site_4_0.ent83" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.mes82 \
        -in $site_4_0 -x 0 -relx 0.045 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.909 -height 0 -relheight 0.411 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent83 \
        -in $site_4_0 -x 0 -relx 0.091 -y 0 -rely 0.632 -width 134 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$site_3_0.lab78" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text "Comptage de pièces" -background #d9d9d9 -height 165 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 220 
    vTcl:DefineAlias "$site_3_0.lab78" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab78
    checkbutton "$site_4_0.che86" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Activer la fonctionnalité" -variable "che86" 
    vTcl:DefineAlias "$site_4_0.che86" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    listbox "$site_4_0.lis84" \
        -background white -disabledforeground #a3a3a3 \
        -font "-family {Courier New} -size 10" -foreground #000000 \
        -height 103 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 84 
    $site_4_0.lis84 configure -font "TkFixedFont"
    $site_4_0.lis84 insert end text
    vTcl:DefineAlias "$site_4_0.lis84" "Listbox4" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab87" \
        -activebackground #d9d9d9 -activeforeground black -background #f9040b \
        -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 12 -weight bold" -foreground #000506 \
        -highlightbackground #d9d9d9 -highlightcolor #000506 -text "---" 
    vTcl:DefineAlias "$site_4_0.lab87" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.che86 \
        -in $site_4_0 -x 0 -relx 0.045 -y 0 -rely 0.121 -width 0 \
        -relwidth 0.777 -height 0 -relheight 0.152 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lis84 \
        -in $site_4_0 -x 0 -relx 0.045 -y 0 -rely 0.303 -width 0 \
        -relwidth 0.382 -height 0 -relheight 0.624 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab87 \
        -in $site_4_0 -x 0 -relx 0.455 -y 0 -rely 0.303 -width 0 \
        -relwidth 0.445 -height 0 -relheight 0.612 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.197 -width 207 \
        -relwidth 0 -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.085 -width 207 \
        -relwidth 0 -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.725 -width 0 \
        -relwidth 0.917 -height 0 -relheight 0.242 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.305 -width 0 \
        -relwidth 0.917 -height 0 -relheight 0.42 -anchor nw \
        -bordermode ignore 
    label "$top.lab48" \
        -activebackground #d9d9d9 -activeforeground #f5f5f5 \
        -background #98cc91 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 14 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Balance app" 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab57 \
        -in $top -x 260 -y 158 -width 330 -relwidth 0 -height 289 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 260 -y 52 -width 330 -relwidth 0 -height 105 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 10 -y 53 -width 240 -relwidth 0 -height 393 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x -4 -y 0 -width 604 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

